### ISSUE TITLE
Can't build from clean checkout

### ISSUE THREAD

**Issue by verasjr195** [prafsoni/greatdanetextbookstore#1]
`git clone http://github...` 
`./activator`
`compile`

Here is the error log:
http://paste.debian.net/plain/169803

I'm using Java8 from webupd8-ppa, not sure what the target is.

**Comment by bodhidharma-joe** [comment]
Seems like you are in the same situation I had on Monday. You may need to
install mongo-java-driver. I can't recall how I installed it. Prafull
helped me install it on my laptop and I installed it myself on my desktop.
But I can't find the button anymore...

Joe

**Comment by prafsoni** [comment]
joe is right you need to install the mongo-java-driver 3.0 
you can install it from project properties under libraries add new from maven
then search mongo-java-driver and download it
