### ISSUE TITLE
So frustrated

### ISSUE THREAD

**Issue by bodhidharma-joe** [prafsoni/greatdanetextbookstore#3]
I have been sitting here overnight to solve this problem. Something is deadly wrong with intellij and play. The compiler keep reporting errors for not resolve some model methods used in my html files, which I have been using with no problem before. I searched this issue online. Many people discuss it, but none of the solutions work for me. I have this issue on both my computers now. One showed this problem yesterday and I switched to another one, which started showing errors after a few hours....

**Comment by prafsoni** [comment]
i have fixed all the issues take a look
